name: dockerize

on:
  push:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  source-gen-and-dockerize:
    runs-on: ubuntu-latest

    steps:
    - name: Grab source
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Generate Full Source Archive
      run: |
        pip install git-archive-all
	./scripts/soy_log_explorer_gen_src_archive.sh

    - name: Create a docker context
      run: |
        mkdir -p /tmp/dockerize/soy_log_explorer
        tar xzf build/soy_log_explorer.src.tar.gz --strip 1 -C /tmp/dockerize/soy_log_explorer

    - name: Log into docker registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin "${{ secrets.DOCKER_REGISTRY_ENDPOINT }}"

    - name: Dockerize bin
      run: |
        docker build \
          -t suhoson/soy_log_explorer:latest \
          -f scripts/Dockerfile /tmp/dockerize

    - name: Push Docker image
      run: docker push suhoson/soy_log_explorer
